### ISSUE TITLE
Use nvm for node install rather than nodesource

### ISSUE THREAD

**Issue by maheshrijal** [maheshrijal/linux-dev-playbook#12]

**Comment by maheshrijal** [comment]
Something like: 
```
- name: Install NVM and Node.js LTS
  hosts: your_target_hosts
  vars:
    nvm_dir: "{{ ansible_env.HOME }}/.nvm"
    nvm_shell_init: |
      export NVM_DIR="{{ ansible_env.HOME }}/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  tasks:
    - name: Install dependencies
      package:
        name:
          - curl
          - git
        state: present
      become: yes

    - name: Check if NVM is already installed
      stat:
        path: "{{ nvm_dir }}/nvm.sh"
      register: nvm_installed

    - name: Download and install NVM
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
      args:
        creates: "{{ nvm_dir }}/nvm.sh"
      when: not nvm_installed.stat.exists

    - name: Install Node.js LTS
      shell: |
        {{ nvm_shell_init }}
        nvm install --lts
      args:
        executable: /bin/bash
      register: node_install
      changed_when: "'is already installed' not in node_install.stdout"

    - name: Set default Node.js to LTS
      shell: |
        {{ nvm_shell_init }}
        nvm alias default lts/*
      args:
        executable: /bin/bash
```
